version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000/api
    # depends_on:
    #   - backend

  db:
    image: postgres:15-alpine
    container_name: pizza_db
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=pizza_builder
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  backend:
      build:
        context: .
        dockerfile: docker/backend/Dockerfile
      ports:
        - "8000:8000"
      volumes:
        - ./backend:/app
      # environment:
      #   - DEBUG=True
      #   - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      #   - DB_NAME=${DB_NAME}
      #   - DB_USER=${DB_USER}
      #   - DB_PASSWORD=${DB_PASSWORD}
      #   - DB_HOST=db
      #   - DB_PORT=5433
      depends_on:
        - db

volumes:
  postgres_data: