# Generated by Django 5.0.2 on 2024-11-27 17:15

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheeseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price_adjustment', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price_adjustment', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('type', models.CharField(choices=[('veggie', 'Vegetable'), ('meat', 'Meat')], max_length=10)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('cheese', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pizza.cheesetype')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pizza.size')),
            ],
        ),
        migrations.CreateModel(
            name='PriceAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('component_type', models.CharField(max_length=50)),
                ('component_name', models.CharField(max_length=100)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('discount_reason', models.CharField(max_length=200)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderTopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_free', models.BooleanField(default=False)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toppings', to='pizza.order')),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pizza.topping')),
            ],
        ),
    ]
